export default function Head() {
  return (
    <>
      <meta charSet="UTF-8" />
      <title>TEKNOLOGIKA</title>
      <meta content="width=device-width, initial-scale=1.0" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
